#!/bin/sh

set -e

BASEDIR=/srv/search.tenders
INIFILE=/etc/search.tenders/ftpsync.ini
LOGFILE=/var/log/search.tenders/ftpsync.log

[ -x $BASEDIR/bin/ocds_ftpsync ] || exit 0

cd $BASEDIR

$BASEDIR/bin/ocds_ftpsync $INIFILE >>$LOGFILE 2>&1
sleep 1
$BASEDIR/bin/circusctl stop
sleep 10
$BASEDIR/bin/circusctl start
sleep 1
