#!/bin/sh
#
# search-tenders     Search API for Prozorro portal
#
# chkconfig: - 50 50
# description: Search API for Prozorro portal
#
### BEGIN INIT INFO
# Provides:          search-tenders
# Required-Start:    $network $remote_fs $syslog $all
# Required-Stop:     $network $remote_fs $syslog  
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable search api for prozorro.gov.ua
### END INIT INFO

set -e

PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions

PIDFILE="/run/search.tenders.circus.pid"
DAEMON="/srv/search.tenders/bin/circusd"
CONTROL="/srv/search.tenders/bin/circusctl"
SOCKET="/srv/search.tenders/var/circus_endpoint"
WORKDIR="/srv/search.tenders/var"

daemon_start() {
    echo "Starting $DAEMON"
    cd $WORKDIR
    $DAEMON --daemon
}

daemon_stop() {
    if [ ! -s $PIDFILE -a ! -S $SOCKET ] ; then
      echo "Service not run, nothing to stop"
      return
    fi
    echo "Stopping $DAEMON pid "`cat $PIDFILE`
    $CONTROL stop
    sleep 3
    $CONTROL quit
    sleep 1
    if [ -s $PIDFILE ] ; then
      kill `$PIDFILE`
      sleep 1
    fi
}

daemon_restart() {
    daemon_stop
    sleep 2
    daemon_start
}

daemon_status() {
    if [ -s $PIDFILE ] ; then
      if ps aux | grep `cat $PIDFILE` | grep circus >/dev/null ; then
        $CONTROL status
      else
        echo dead, but pidfile exists
      fi
    else
      echo dead
    fi
}

case "$1" in
    start)  daemon_start ;;
    stop)   daemon_stop ;;
    status) daemon_status ;;
    restart|reload|force-reload) daemon_restart ;;
    *) echo "Usage: $0 {start|stop|status|restart}" 1>&2 ;;
esac

